# This file is the default config
# Use it as template to create your own config.yml

AccessControl:
    endpoint: "https://ca.42nice.fr/api"
    testpath: "/events/?length=1"
    username: "YOUR_CA_USERNAME"
    password: "YOUR_CA_PASSWORD"

42apiV2:
    tokenUrl: "https://api.intra.42.fr/oauth/token"
    endpoint: "https://api.intra.42.fr/v2"
    testpath: "/campus/41"
    uid: "YOUR_42API_APP_UID"
    secret: "YOUR_42API_APP_TOKEN"
    scope: "public"
    apprenticeProjects: ["2561", "2562", "2563", "2564"]

42Attendance:
    autoPost: false
    tokenUrl: "https://auth.42.fr/auth/realms/staff-42/protocol/openid-connect/token"
    endpoint: "https://chronos.42.fr/api/v1"
    testpath: "/campus/41/sources"
    uid: "YOUR_42API_APP_UID"
    secret: "YOUR_42API_APP_TOKEN"
    username: "YOUR_42STAFF_USERNAME"
    password: "YOUR_42STAFF_PASSWORD"

mailer:
    smtp_server: ""
    smtp_port: 4242
    smtp_auth: false
    smtp_user: ""
    smtp_pass: ""
    smtp_tls: true
    helo: ""
    from_name: ""
    from_mail: ""
    recipients: ["heinz@42nice.fr"]

watchtime:
    monday:     [["07:30:00", "20:30:00"]]
    tuesday:    [["07:30:00", "20:30:00"]]
    wednesday:  [["07:30:00", "20:30:00"]]
    thursday:   [["07:30:00", "20:30:00"]]
    friday:     [["07:30:00", "20:30:00"]]
    saturday:   []
    sunday:     []
